// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sourcenetwork/acp_core/playground/sandbox.proto

package playground

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Handle is an opaque identifier to an execution environment in the service (aka sandbox)
type Handle struct {
	Handle uint64 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
}

func (m *Handle) Reset()         { *m = Handle{} }
func (m *Handle) String() string { return proto.CompactTextString(m) }
func (*Handle) ProtoMessage()    {}
func (*Handle) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ae4e460be0ca31, []int{0}
}
func (m *Handle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Handle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Handle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Handle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handle.Merge(m, src)
}
func (m *Handle) XXX_Size() int {
	return m.Size()
}
func (m *Handle) XXX_DiscardUnknown() {
	xxx_messageInfo_Handle.DiscardUnknown(m)
}

var xxx_messageInfo_Handle proto.InternalMessageInfo

func (m *Handle) GetHandle() uint64 {
	if m != nil {
		return m.Handle
	}
	return 0
}

// SandboxRecord represents an instance of a sandbox
type SandboxRecord struct {
	// Handle is an opaque identifier to a sandbox
	Handle *Handle `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// name is a user given designation to a sandbox
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *SandboxRecord) Reset()         { *m = SandboxRecord{} }
func (m *SandboxRecord) String() string { return proto.CompactTextString(m) }
func (*SandboxRecord) ProtoMessage()    {}
func (*SandboxRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ae4e460be0ca31, []int{1}
}
func (m *SandboxRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SandboxRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SandboxRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SandboxRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandboxRecord.Merge(m, src)
}
func (m *SandboxRecord) XXX_Size() int {
	return m.Size()
}
func (m *SandboxRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SandboxRecord.DiscardUnknown(m)
}

var xxx_messageInfo_SandboxRecord proto.InternalMessageInfo

func (m *SandboxRecord) GetHandle() *Handle {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *SandboxRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// SandboxState encapsulates all the data necessary to create a Sandbox
type SandboxState struct {
	PolicyDefinition string `protobuf:"bytes,1,opt,name=policy_definition,json=policyDefinition,proto3" json:"policy_definition,omitempty"`
	Relationships    string `protobuf:"bytes,2,opt,name=relationships,proto3" json:"relationships,omitempty"`
	PolicyTheorem    string `protobuf:"bytes,3,opt,name=policy_theorem,json=policyTheorem,proto3" json:"policy_theorem,omitempty"`
}

func (m *SandboxState) Reset()         { *m = SandboxState{} }
func (m *SandboxState) String() string { return proto.CompactTextString(m) }
func (*SandboxState) ProtoMessage()    {}
func (*SandboxState) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ae4e460be0ca31, []int{2}
}
func (m *SandboxState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SandboxState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SandboxState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SandboxState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandboxState.Merge(m, src)
}
func (m *SandboxState) XXX_Size() int {
	return m.Size()
}
func (m *SandboxState) XXX_DiscardUnknown() {
	xxx_messageInfo_SandboxState.DiscardUnknown(m)
}

var xxx_messageInfo_SandboxState proto.InternalMessageInfo

func (m *SandboxState) GetPolicyDefinition() string {
	if m != nil {
		return m.PolicyDefinition
	}
	return ""
}

func (m *SandboxState) GetRelationships() string {
	if m != nil {
		return m.Relationships
	}
	return ""
}

func (m *SandboxState) GetPolicyTheorem() string {
	if m != nil {
		return m.PolicyTheorem
	}
	return ""
}

func init() {
	proto.RegisterType((*Handle)(nil), "sourcenetwork.acp_core.playground.Handle")
	proto.RegisterType((*SandboxRecord)(nil), "sourcenetwork.acp_core.playground.SandboxRecord")
	proto.RegisterType((*SandboxState)(nil), "sourcenetwork.acp_core.playground.SandboxState")
}

func init() {
	proto.RegisterFile("sourcenetwork/acp_core/playground/sandbox.proto", fileDescriptor_96ae4e460be0ca31)
}

var fileDescriptor_96ae4e460be0ca31 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x1c, 0xc4, 0xeb, 0xef, 0xab, 0x2a, 0xd5, 0x50, 0x04, 0x1e, 0x50, 0x27, 0x2b, 0x44, 0x20, 0x15,
	0x21, 0x39, 0x08, 0x9e, 0x00, 0xc4, 0x80, 0x18, 0x53, 0x26, 0x96, 0xca, 0x71, 0xdc, 0xc4, 0x6a,
	0xe2, 0x7f, 0xe4, 0x38, 0x82, 0xbe, 0x01, 0x23, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0x25, 0x2f, 0x82,
	0x88, 0x53, 0x20, 0x03, 0x62, 0x3b, 0x9f, 0xff, 0x77, 0xbf, 0xe1, 0x70, 0x50, 0x42, 0x65, 0x84,
	0xd4, 0xd2, 0x3e, 0x82, 0x59, 0x05, 0x5c, 0x14, 0x0b, 0x01, 0x46, 0x06, 0x45, 0xc6, 0xd7, 0x89,
	0x81, 0x4a, 0xc7, 0x41, 0xc9, 0x75, 0x1c, 0xc1, 0x13, 0x2b, 0x0c, 0x58, 0x20, 0x47, 0xbd, 0x00,
	0xdb, 0x06, 0xd8, 0x77, 0xc0, 0xf7, 0xf0, 0xe8, 0x96, 0xeb, 0x38, 0x93, 0xe4, 0x10, 0x8f, 0xd2,
	0x56, 0x4d, 0x91, 0x87, 0x66, 0xc3, 0xb0, 0x7b, 0xf9, 0x4b, 0x3c, 0x99, 0xbb, 0xd6, 0x50, 0x0a,
	0x30, 0x31, 0xb9, 0xea, 0x1d, 0xee, 0x5c, 0x9c, 0xb2, 0x3f, 0x31, 0xcc, 0x31, 0xb6, 0x9d, 0x84,
	0xe0, 0xa1, 0xe6, 0xb9, 0x9c, 0xfe, 0xf3, 0xd0, 0x6c, 0x1c, 0xb6, 0xda, 0x7f, 0x46, 0x78, 0xb7,
	0x03, 0xcd, 0x2d, 0xb7, 0x92, 0x9c, 0xe1, 0x83, 0x02, 0x32, 0x25, 0xd6, 0x8b, 0x58, 0x2e, 0x95,
	0x56, 0x56, 0x81, 0x6e, 0x91, 0xe3, 0x70, 0xdf, 0x7d, 0xdc, 0x7c, 0xf9, 0xe4, 0x18, 0x4f, 0x8c,
	0xcc, 0xf8, 0xa7, 0x2e, 0x53, 0x55, 0x94, 0x5d, 0x75, 0xdf, 0x24, 0x27, 0x78, 0xaf, 0xab, 0xb4,
	0xa9, 0x04, 0x23, 0xf3, 0xe9, 0x7f, 0x77, 0xe6, 0xdc, 0x7b, 0x67, 0x5e, 0xdf, 0xbd, 0xd6, 0x14,
	0x6d, 0x6a, 0x8a, 0xde, 0x6b, 0x8a, 0x5e, 0x1a, 0x3a, 0xd8, 0x34, 0x74, 0xf0, 0xd6, 0xd0, 0xc1,
	0xc3, 0x79, 0xa2, 0x6c, 0x5a, 0x45, 0x4c, 0x40, 0xfe, 0xeb, 0x1a, 0xab, 0xe4, 0xc7, 0x22, 0xd1,
	0xa8, 0x9d, 0xe2, 0xf2, 0x23, 0x00, 0x00, 0xff, 0xff, 0x72, 0x9d, 0xb7, 0x58, 0xbd, 0x01, 0x00,
	0x00,
}

func (m *Handle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Handle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Handle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Handle != 0 {
		i = encodeVarintSandbox(dAtA, i, uint64(m.Handle))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SandboxRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SandboxRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SandboxRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSandbox(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Handle != nil {
		{
			size, err := m.Handle.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSandbox(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SandboxState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SandboxState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SandboxState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PolicyTheorem) > 0 {
		i -= len(m.PolicyTheorem)
		copy(dAtA[i:], m.PolicyTheorem)
		i = encodeVarintSandbox(dAtA, i, uint64(len(m.PolicyTheorem)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Relationships) > 0 {
		i -= len(m.Relationships)
		copy(dAtA[i:], m.Relationships)
		i = encodeVarintSandbox(dAtA, i, uint64(len(m.Relationships)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PolicyDefinition) > 0 {
		i -= len(m.PolicyDefinition)
		copy(dAtA[i:], m.PolicyDefinition)
		i = encodeVarintSandbox(dAtA, i, uint64(len(m.PolicyDefinition)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSandbox(dAtA []byte, offset int, v uint64) int {
	offset -= sovSandbox(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Handle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Handle != 0 {
		n += 1 + sovSandbox(uint64(m.Handle))
	}
	return n
}

func (m *SandboxRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Handle != nil {
		l = m.Handle.Size()
		n += 1 + l + sovSandbox(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSandbox(uint64(l))
	}
	return n
}

func (m *SandboxState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PolicyDefinition)
	if l > 0 {
		n += 1 + l + sovSandbox(uint64(l))
	}
	l = len(m.Relationships)
	if l > 0 {
		n += 1 + l + sovSandbox(uint64(l))
	}
	l = len(m.PolicyTheorem)
	if l > 0 {
		n += 1 + l + sovSandbox(uint64(l))
	}
	return n
}

func sovSandbox(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSandbox(x uint64) (n int) {
	return sovSandbox(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Handle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSandbox
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Handle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Handle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handle", wireType)
			}
			m.Handle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Handle |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSandbox(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSandbox
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SandboxRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSandbox
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SandboxRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SandboxRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSandbox
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSandbox
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Handle == nil {
				m.Handle = &Handle{}
			}
			if err := m.Handle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSandbox
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSandbox
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSandbox(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSandbox
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SandboxState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSandbox
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SandboxState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SandboxState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyDefinition", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSandbox
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSandbox
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyDefinition = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relationships", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSandbox
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSandbox
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relationships = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyTheorem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSandbox
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSandbox
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyTheorem = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSandbox(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSandbox
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSandbox(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSandbox
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSandbox
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSandbox
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSandbox
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSandbox
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSandbox        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSandbox          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSandbox = fmt.Errorf("proto: unexpected end of group")
)
