// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package types

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sort "sort"
	sync "sync"
)

var _ protoreflect.Map = (*_PolicyCatalogue_1_map)(nil)

type _PolicyCatalogue_1_map struct {
	m *map[string]*ResourceCatalogue
}

func (x *_PolicyCatalogue_1_map) Len() int {
	if x.m == nil {
		return 0
	}
	return len(*x.m)
}

func (x *_PolicyCatalogue_1_map) Range(f func(protoreflect.MapKey, protoreflect.Value) bool) {
	if x.m == nil {
		return
	}
	for k, v := range *x.m {
		mapKey := (protoreflect.MapKey)(protoreflect.ValueOfString(k))
		mapValue := protoreflect.ValueOfMessage(v.ProtoReflect())
		if !f(mapKey, mapValue) {
			break
		}
	}
}

func (x *_PolicyCatalogue_1_map) Has(key protoreflect.MapKey) bool {
	if x.m == nil {
		return false
	}
	keyUnwrapped := key.String()
	concreteValue := keyUnwrapped
	_, ok := (*x.m)[concreteValue]
	return ok
}

func (x *_PolicyCatalogue_1_map) Clear(key protoreflect.MapKey) {
	if x.m == nil {
		return
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	delete(*x.m, concreteKey)
}

func (x *_PolicyCatalogue_1_map) Get(key protoreflect.MapKey) protoreflect.Value {
	if x.m == nil {
		return protoreflect.Value{}
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	v, ok := (*x.m)[concreteKey]
	if !ok {
		return protoreflect.Value{}
	}
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_PolicyCatalogue_1_map) Set(key protoreflect.MapKey, value protoreflect.Value) {
	if !key.IsValid() || !value.IsValid() {
		panic("invalid key or value provided")
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*ResourceCatalogue)
	(*x.m)[concreteKey] = concreteValue
}

func (x *_PolicyCatalogue_1_map) Mutable(key protoreflect.MapKey) protoreflect.Value {
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	v, ok := (*x.m)[concreteKey]
	if ok {
		return protoreflect.ValueOfMessage(v.ProtoReflect())
	}
	newValue := new(ResourceCatalogue)
	(*x.m)[concreteKey] = newValue
	return protoreflect.ValueOfMessage(newValue.ProtoReflect())
}

func (x *_PolicyCatalogue_1_map) NewValue() protoreflect.Value {
	v := new(ResourceCatalogue)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_PolicyCatalogue_1_map) IsValid() bool {
	return x.m != nil
}

var _ protoreflect.List = (*_PolicyCatalogue_3_list)(nil)

type _PolicyCatalogue_3_list struct {
	list *[]string
}

func (x *_PolicyCatalogue_3_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_PolicyCatalogue_3_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_PolicyCatalogue_3_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_PolicyCatalogue_3_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_PolicyCatalogue_3_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message PolicyCatalogue at list field Actors as it is not of Message kind"))
}

func (x *_PolicyCatalogue_3_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_PolicyCatalogue_3_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_PolicyCatalogue_3_list) IsValid() bool {
	return x.list != nil
}

var (
	md_PolicyCatalogue                     protoreflect.MessageDescriptor
	fd_PolicyCatalogue_resource_catalogue  protoreflect.FieldDescriptor
	fd_PolicyCatalogue_actor_resource_name protoreflect.FieldDescriptor
	fd_PolicyCatalogue_actors              protoreflect.FieldDescriptor
)

func init() {
	file_sourcenetwork_acp_core_catalogue_proto_init()
	md_PolicyCatalogue = File_sourcenetwork_acp_core_catalogue_proto.Messages().ByName("PolicyCatalogue")
	fd_PolicyCatalogue_resource_catalogue = md_PolicyCatalogue.Fields().ByName("resource_catalogue")
	fd_PolicyCatalogue_actor_resource_name = md_PolicyCatalogue.Fields().ByName("actor_resource_name")
	fd_PolicyCatalogue_actors = md_PolicyCatalogue.Fields().ByName("actors")
}

var _ protoreflect.Message = (*fastReflection_PolicyCatalogue)(nil)

type fastReflection_PolicyCatalogue PolicyCatalogue

func (x *PolicyCatalogue) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PolicyCatalogue)(x)
}

func (x *PolicyCatalogue) slowProtoReflect() protoreflect.Message {
	mi := &file_sourcenetwork_acp_core_catalogue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PolicyCatalogue_messageType fastReflection_PolicyCatalogue_messageType
var _ protoreflect.MessageType = fastReflection_PolicyCatalogue_messageType{}

type fastReflection_PolicyCatalogue_messageType struct{}

func (x fastReflection_PolicyCatalogue_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PolicyCatalogue)(nil)
}
func (x fastReflection_PolicyCatalogue_messageType) New() protoreflect.Message {
	return new(fastReflection_PolicyCatalogue)
}
func (x fastReflection_PolicyCatalogue_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PolicyCatalogue
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PolicyCatalogue) Descriptor() protoreflect.MessageDescriptor {
	return md_PolicyCatalogue
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PolicyCatalogue) Type() protoreflect.MessageType {
	return _fastReflection_PolicyCatalogue_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PolicyCatalogue) New() protoreflect.Message {
	return new(fastReflection_PolicyCatalogue)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PolicyCatalogue) Interface() protoreflect.ProtoMessage {
	return (*PolicyCatalogue)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PolicyCatalogue) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.ResourceCatalogue) != 0 {
		value := protoreflect.ValueOfMap(&_PolicyCatalogue_1_map{m: &x.ResourceCatalogue})
		if !f(fd_PolicyCatalogue_resource_catalogue, value) {
			return
		}
	}
	if x.ActorResourceName != "" {
		value := protoreflect.ValueOfString(x.ActorResourceName)
		if !f(fd_PolicyCatalogue_actor_resource_name, value) {
			return
		}
	}
	if len(x.Actors) != 0 {
		value := protoreflect.ValueOfList(&_PolicyCatalogue_3_list{list: &x.Actors})
		if !f(fd_PolicyCatalogue_actors, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PolicyCatalogue) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue":
		return len(x.ResourceCatalogue) != 0
	case "sourcenetwork.acp_core.PolicyCatalogue.actor_resource_name":
		return x.ActorResourceName != ""
	case "sourcenetwork.acp_core.PolicyCatalogue.actors":
		return len(x.Actors) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.PolicyCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.PolicyCatalogue does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PolicyCatalogue) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue":
		x.ResourceCatalogue = nil
	case "sourcenetwork.acp_core.PolicyCatalogue.actor_resource_name":
		x.ActorResourceName = ""
	case "sourcenetwork.acp_core.PolicyCatalogue.actors":
		x.Actors = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.PolicyCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.PolicyCatalogue does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PolicyCatalogue) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue":
		if len(x.ResourceCatalogue) == 0 {
			return protoreflect.ValueOfMap(&_PolicyCatalogue_1_map{})
		}
		mapValue := &_PolicyCatalogue_1_map{m: &x.ResourceCatalogue}
		return protoreflect.ValueOfMap(mapValue)
	case "sourcenetwork.acp_core.PolicyCatalogue.actor_resource_name":
		value := x.ActorResourceName
		return protoreflect.ValueOfString(value)
	case "sourcenetwork.acp_core.PolicyCatalogue.actors":
		if len(x.Actors) == 0 {
			return protoreflect.ValueOfList(&_PolicyCatalogue_3_list{})
		}
		listValue := &_PolicyCatalogue_3_list{list: &x.Actors}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.PolicyCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.PolicyCatalogue does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PolicyCatalogue) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue":
		mv := value.Map()
		cmv := mv.(*_PolicyCatalogue_1_map)
		x.ResourceCatalogue = *cmv.m
	case "sourcenetwork.acp_core.PolicyCatalogue.actor_resource_name":
		x.ActorResourceName = value.Interface().(string)
	case "sourcenetwork.acp_core.PolicyCatalogue.actors":
		lv := value.List()
		clv := lv.(*_PolicyCatalogue_3_list)
		x.Actors = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.PolicyCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.PolicyCatalogue does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PolicyCatalogue) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue":
		if x.ResourceCatalogue == nil {
			x.ResourceCatalogue = make(map[string]*ResourceCatalogue)
		}
		value := &_PolicyCatalogue_1_map{m: &x.ResourceCatalogue}
		return protoreflect.ValueOfMap(value)
	case "sourcenetwork.acp_core.PolicyCatalogue.actors":
		if x.Actors == nil {
			x.Actors = []string{}
		}
		value := &_PolicyCatalogue_3_list{list: &x.Actors}
		return protoreflect.ValueOfList(value)
	case "sourcenetwork.acp_core.PolicyCatalogue.actor_resource_name":
		panic(fmt.Errorf("field actor_resource_name of message sourcenetwork.acp_core.PolicyCatalogue is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.PolicyCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.PolicyCatalogue does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PolicyCatalogue) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue":
		m := make(map[string]*ResourceCatalogue)
		return protoreflect.ValueOfMap(&_PolicyCatalogue_1_map{m: &m})
	case "sourcenetwork.acp_core.PolicyCatalogue.actor_resource_name":
		return protoreflect.ValueOfString("")
	case "sourcenetwork.acp_core.PolicyCatalogue.actors":
		list := []string{}
		return protoreflect.ValueOfList(&_PolicyCatalogue_3_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.PolicyCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.PolicyCatalogue does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PolicyCatalogue) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sourcenetwork.acp_core.PolicyCatalogue", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PolicyCatalogue) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PolicyCatalogue) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PolicyCatalogue) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PolicyCatalogue) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PolicyCatalogue)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.ResourceCatalogue) > 0 {
			SiZeMaP := func(k string, v *ResourceCatalogue) {
				l := 0
				if v != nil {
					l = options.Size(v)
				}
				l += 1 + runtime.Sov(uint64(l))
				mapEntrySize := 1 + len(k) + runtime.Sov(uint64(len(k))) + l
				n += mapEntrySize + 1 + runtime.Sov(uint64(mapEntrySize))
			}
			if options.Deterministic {
				sortme := make([]string, 0, len(x.ResourceCatalogue))
				for k := range x.ResourceCatalogue {
					sortme = append(sortme, k)
				}
				sort.Strings(sortme)
				for _, k := range sortme {
					v := x.ResourceCatalogue[k]
					SiZeMaP(k, v)
				}
			} else {
				for k, v := range x.ResourceCatalogue {
					SiZeMaP(k, v)
				}
			}
		}
		l = len(x.ActorResourceName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Actors) > 0 {
			for _, s := range x.Actors {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PolicyCatalogue)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Actors) > 0 {
			for iNdEx := len(x.Actors) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Actors[iNdEx])
				copy(dAtA[i:], x.Actors[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Actors[iNdEx])))
				i--
				dAtA[i] = 0x1a
			}
		}
		if len(x.ActorResourceName) > 0 {
			i -= len(x.ActorResourceName)
			copy(dAtA[i:], x.ActorResourceName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ActorResourceName)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.ResourceCatalogue) > 0 {
			MaRsHaLmAp := func(k string, v *ResourceCatalogue) (protoiface.MarshalOutput, error) {
				baseI := i
				encoded, err := options.Marshal(v)
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x12
				i -= len(k)
				copy(dAtA[i:], k)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(k)))
				i--
				dAtA[i] = 0xa
				i = runtime.EncodeVarint(dAtA, i, uint64(baseI-i))
				i--
				dAtA[i] = 0xa
				return protoiface.MarshalOutput{}, nil
			}
			if options.Deterministic {
				keysForResourceCatalogue := make([]string, 0, len(x.ResourceCatalogue))
				for k := range x.ResourceCatalogue {
					keysForResourceCatalogue = append(keysForResourceCatalogue, string(k))
				}
				sort.Slice(keysForResourceCatalogue, func(i, j int) bool {
					return keysForResourceCatalogue[i] < keysForResourceCatalogue[j]
				})
				for iNdEx := len(keysForResourceCatalogue) - 1; iNdEx >= 0; iNdEx-- {
					v := x.ResourceCatalogue[string(keysForResourceCatalogue[iNdEx])]
					out, err := MaRsHaLmAp(keysForResourceCatalogue[iNdEx], v)
					if err != nil {
						return out, err
					}
				}
			} else {
				for k := range x.ResourceCatalogue {
					v := x.ResourceCatalogue[k]
					out, err := MaRsHaLmAp(k, v)
					if err != nil {
						return out, err
					}
				}
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PolicyCatalogue)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PolicyCatalogue: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PolicyCatalogue: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ResourceCatalogue", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.ResourceCatalogue == nil {
					x.ResourceCatalogue = make(map[string]*ResourceCatalogue)
				}
				var mapkey string
				var mapvalue *ResourceCatalogue
				for iNdEx < postIndex {
					entryPreIndex := iNdEx
					var wire uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
						}
						if iNdEx >= l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						wire |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					fieldNum := int32(wire >> 3)
					if fieldNum == 1 {
						var stringLenmapkey uint64
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							stringLenmapkey |= uint64(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
						intStringLenmapkey := int(stringLenmapkey)
						if intStringLenmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						postStringIndexmapkey := iNdEx + intStringLenmapkey
						if postStringIndexmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if postStringIndexmapkey > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
						iNdEx = postStringIndexmapkey
					} else if fieldNum == 2 {
						var mapmsglen int
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							mapmsglen |= int(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
						if mapmsglen < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						postmsgIndex := iNdEx + mapmsglen
						if postmsgIndex < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if postmsgIndex > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapvalue = &ResourceCatalogue{}
						if err := options.Unmarshal(dAtA[iNdEx:postmsgIndex], mapvalue); err != nil {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
						}
						iNdEx = postmsgIndex
					} else {
						iNdEx = entryPreIndex
						skippy, err := runtime.Skip(dAtA[iNdEx:])
						if err != nil {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
						}
						if (skippy < 0) || (iNdEx+skippy) < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if (iNdEx + skippy) > postIndex {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						iNdEx += skippy
					}
				}
				x.ResourceCatalogue[mapkey] = mapvalue
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ActorResourceName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ActorResourceName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Actors", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Actors = append(x.Actors, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_ResourceCatalogue_1_list)(nil)

type _ResourceCatalogue_1_list struct {
	list *[]string
}

func (x *_ResourceCatalogue_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_ResourceCatalogue_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_ResourceCatalogue_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_ResourceCatalogue_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_ResourceCatalogue_1_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message ResourceCatalogue at list field Permissions as it is not of Message kind"))
}

func (x *_ResourceCatalogue_1_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_ResourceCatalogue_1_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_ResourceCatalogue_1_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_ResourceCatalogue_2_list)(nil)

type _ResourceCatalogue_2_list struct {
	list *[]string
}

func (x *_ResourceCatalogue_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_ResourceCatalogue_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_ResourceCatalogue_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_ResourceCatalogue_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_ResourceCatalogue_2_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message ResourceCatalogue at list field Relations as it is not of Message kind"))
}

func (x *_ResourceCatalogue_2_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_ResourceCatalogue_2_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_ResourceCatalogue_2_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_ResourceCatalogue_3_list)(nil)

type _ResourceCatalogue_3_list struct {
	list *[]string
}

func (x *_ResourceCatalogue_3_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_ResourceCatalogue_3_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_ResourceCatalogue_3_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_ResourceCatalogue_3_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_ResourceCatalogue_3_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message ResourceCatalogue at list field ObjectIds as it is not of Message kind"))
}

func (x *_ResourceCatalogue_3_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_ResourceCatalogue_3_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_ResourceCatalogue_3_list) IsValid() bool {
	return x.list != nil
}

var (
	md_ResourceCatalogue             protoreflect.MessageDescriptor
	fd_ResourceCatalogue_permissions protoreflect.FieldDescriptor
	fd_ResourceCatalogue_relations   protoreflect.FieldDescriptor
	fd_ResourceCatalogue_object_ids  protoreflect.FieldDescriptor
)

func init() {
	file_sourcenetwork_acp_core_catalogue_proto_init()
	md_ResourceCatalogue = File_sourcenetwork_acp_core_catalogue_proto.Messages().ByName("ResourceCatalogue")
	fd_ResourceCatalogue_permissions = md_ResourceCatalogue.Fields().ByName("permissions")
	fd_ResourceCatalogue_relations = md_ResourceCatalogue.Fields().ByName("relations")
	fd_ResourceCatalogue_object_ids = md_ResourceCatalogue.Fields().ByName("object_ids")
}

var _ protoreflect.Message = (*fastReflection_ResourceCatalogue)(nil)

type fastReflection_ResourceCatalogue ResourceCatalogue

func (x *ResourceCatalogue) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ResourceCatalogue)(x)
}

func (x *ResourceCatalogue) slowProtoReflect() protoreflect.Message {
	mi := &file_sourcenetwork_acp_core_catalogue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ResourceCatalogue_messageType fastReflection_ResourceCatalogue_messageType
var _ protoreflect.MessageType = fastReflection_ResourceCatalogue_messageType{}

type fastReflection_ResourceCatalogue_messageType struct{}

func (x fastReflection_ResourceCatalogue_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ResourceCatalogue)(nil)
}
func (x fastReflection_ResourceCatalogue_messageType) New() protoreflect.Message {
	return new(fastReflection_ResourceCatalogue)
}
func (x fastReflection_ResourceCatalogue_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ResourceCatalogue
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ResourceCatalogue) Descriptor() protoreflect.MessageDescriptor {
	return md_ResourceCatalogue
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ResourceCatalogue) Type() protoreflect.MessageType {
	return _fastReflection_ResourceCatalogue_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ResourceCatalogue) New() protoreflect.Message {
	return new(fastReflection_ResourceCatalogue)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ResourceCatalogue) Interface() protoreflect.ProtoMessage {
	return (*ResourceCatalogue)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ResourceCatalogue) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Permissions) != 0 {
		value := protoreflect.ValueOfList(&_ResourceCatalogue_1_list{list: &x.Permissions})
		if !f(fd_ResourceCatalogue_permissions, value) {
			return
		}
	}
	if len(x.Relations) != 0 {
		value := protoreflect.ValueOfList(&_ResourceCatalogue_2_list{list: &x.Relations})
		if !f(fd_ResourceCatalogue_relations, value) {
			return
		}
	}
	if len(x.ObjectIds) != 0 {
		value := protoreflect.ValueOfList(&_ResourceCatalogue_3_list{list: &x.ObjectIds})
		if !f(fd_ResourceCatalogue_object_ids, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ResourceCatalogue) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.ResourceCatalogue.permissions":
		return len(x.Permissions) != 0
	case "sourcenetwork.acp_core.ResourceCatalogue.relations":
		return len(x.Relations) != 0
	case "sourcenetwork.acp_core.ResourceCatalogue.object_ids":
		return len(x.ObjectIds) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.ResourceCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.ResourceCatalogue does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResourceCatalogue) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.ResourceCatalogue.permissions":
		x.Permissions = nil
	case "sourcenetwork.acp_core.ResourceCatalogue.relations":
		x.Relations = nil
	case "sourcenetwork.acp_core.ResourceCatalogue.object_ids":
		x.ObjectIds = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.ResourceCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.ResourceCatalogue does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ResourceCatalogue) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sourcenetwork.acp_core.ResourceCatalogue.permissions":
		if len(x.Permissions) == 0 {
			return protoreflect.ValueOfList(&_ResourceCatalogue_1_list{})
		}
		listValue := &_ResourceCatalogue_1_list{list: &x.Permissions}
		return protoreflect.ValueOfList(listValue)
	case "sourcenetwork.acp_core.ResourceCatalogue.relations":
		if len(x.Relations) == 0 {
			return protoreflect.ValueOfList(&_ResourceCatalogue_2_list{})
		}
		listValue := &_ResourceCatalogue_2_list{list: &x.Relations}
		return protoreflect.ValueOfList(listValue)
	case "sourcenetwork.acp_core.ResourceCatalogue.object_ids":
		if len(x.ObjectIds) == 0 {
			return protoreflect.ValueOfList(&_ResourceCatalogue_3_list{})
		}
		listValue := &_ResourceCatalogue_3_list{list: &x.ObjectIds}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.ResourceCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.ResourceCatalogue does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResourceCatalogue) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.ResourceCatalogue.permissions":
		lv := value.List()
		clv := lv.(*_ResourceCatalogue_1_list)
		x.Permissions = *clv.list
	case "sourcenetwork.acp_core.ResourceCatalogue.relations":
		lv := value.List()
		clv := lv.(*_ResourceCatalogue_2_list)
		x.Relations = *clv.list
	case "sourcenetwork.acp_core.ResourceCatalogue.object_ids":
		lv := value.List()
		clv := lv.(*_ResourceCatalogue_3_list)
		x.ObjectIds = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.ResourceCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.ResourceCatalogue does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResourceCatalogue) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.ResourceCatalogue.permissions":
		if x.Permissions == nil {
			x.Permissions = []string{}
		}
		value := &_ResourceCatalogue_1_list{list: &x.Permissions}
		return protoreflect.ValueOfList(value)
	case "sourcenetwork.acp_core.ResourceCatalogue.relations":
		if x.Relations == nil {
			x.Relations = []string{}
		}
		value := &_ResourceCatalogue_2_list{list: &x.Relations}
		return protoreflect.ValueOfList(value)
	case "sourcenetwork.acp_core.ResourceCatalogue.object_ids":
		if x.ObjectIds == nil {
			x.ObjectIds = []string{}
		}
		value := &_ResourceCatalogue_3_list{list: &x.ObjectIds}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.ResourceCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.ResourceCatalogue does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ResourceCatalogue) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sourcenetwork.acp_core.ResourceCatalogue.permissions":
		list := []string{}
		return protoreflect.ValueOfList(&_ResourceCatalogue_1_list{list: &list})
	case "sourcenetwork.acp_core.ResourceCatalogue.relations":
		list := []string{}
		return protoreflect.ValueOfList(&_ResourceCatalogue_2_list{list: &list})
	case "sourcenetwork.acp_core.ResourceCatalogue.object_ids":
		list := []string{}
		return protoreflect.ValueOfList(&_ResourceCatalogue_3_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sourcenetwork.acp_core.ResourceCatalogue"))
		}
		panic(fmt.Errorf("message sourcenetwork.acp_core.ResourceCatalogue does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ResourceCatalogue) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sourcenetwork.acp_core.ResourceCatalogue", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ResourceCatalogue) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ResourceCatalogue) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ResourceCatalogue) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ResourceCatalogue) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ResourceCatalogue)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.Permissions) > 0 {
			for _, s := range x.Permissions {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.Relations) > 0 {
			for _, s := range x.Relations {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.ObjectIds) > 0 {
			for _, s := range x.ObjectIds {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ResourceCatalogue)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ObjectIds) > 0 {
			for iNdEx := len(x.ObjectIds) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.ObjectIds[iNdEx])
				copy(dAtA[i:], x.ObjectIds[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ObjectIds[iNdEx])))
				i--
				dAtA[i] = 0x1a
			}
		}
		if len(x.Relations) > 0 {
			for iNdEx := len(x.Relations) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Relations[iNdEx])
				copy(dAtA[i:], x.Relations[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Relations[iNdEx])))
				i--
				dAtA[i] = 0x12
			}
		}
		if len(x.Permissions) > 0 {
			for iNdEx := len(x.Permissions) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Permissions[iNdEx])
				copy(dAtA[i:], x.Permissions[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Permissions[iNdEx])))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ResourceCatalogue)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ResourceCatalogue: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ResourceCatalogue: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Permissions", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Permissions = append(x.Permissions, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Relations", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Relations = append(x.Relations, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ObjectIds", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ObjectIds = append(x.ObjectIds, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: sourcenetwork/acp_core/catalogue.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyCatalogue represents a lookup table for entities definedw withing a Policy
type PolicyCatalogue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceCatalogue map[string]*ResourceCatalogue `protobuf:"bytes,1,rep,name=resource_catalogue,json=resourceCatalogue,proto3" json:"resource_catalogue,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ActorResourceName string                        `protobuf:"bytes,2,opt,name=actor_resource_name,json=actorResourceName,proto3" json:"actor_resource_name,omitempty"`
	Actors            []string                      `protobuf:"bytes,3,rep,name=actors,proto3" json:"actors,omitempty"`
}

func (x *PolicyCatalogue) Reset() {
	*x = PolicyCatalogue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sourcenetwork_acp_core_catalogue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyCatalogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyCatalogue) ProtoMessage() {}

// Deprecated: Use PolicyCatalogue.ProtoReflect.Descriptor instead.
func (*PolicyCatalogue) Descriptor() ([]byte, []int) {
	return file_sourcenetwork_acp_core_catalogue_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyCatalogue) GetResourceCatalogue() map[string]*ResourceCatalogue {
	if x != nil {
		return x.ResourceCatalogue
	}
	return nil
}

func (x *PolicyCatalogue) GetActorResourceName() string {
	if x != nil {
		return x.ActorResourceName
	}
	return ""
}

func (x *PolicyCatalogue) GetActors() []string {
	if x != nil {
		return x.Actors
	}
	return nil
}

// ResourceCatalogue models the set of known objects, permissions and relations for a Resource within a Policy
type ResourceCatalogue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Relations   []string `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	ObjectIds   []string `protobuf:"bytes,3,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
}

func (x *ResourceCatalogue) Reset() {
	*x = ResourceCatalogue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sourcenetwork_acp_core_catalogue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceCatalogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCatalogue) ProtoMessage() {}

// Deprecated: Use ResourceCatalogue.ProtoReflect.Descriptor instead.
func (*ResourceCatalogue) Descriptor() ([]byte, []int) {
	return file_sourcenetwork_acp_core_catalogue_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceCatalogue) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ResourceCatalogue) GetRelations() []string {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *ResourceCatalogue) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

var File_sourcenetwork_acp_core_catalogue_proto protoreflect.FileDescriptor

var file_sourcenetwork_acp_core_catalogue_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f,
	0x61, 0x63, 0x70, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x61, 0x63, 0x70, 0x5f, 0x63, 0x6f, 0x72, 0x65,
	0x22, 0xb9, 0x02, 0x0a, 0x0f, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x75, 0x65, 0x12, 0x6d, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x3e, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x61, 0x63, 0x70, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x11, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x1a, 0x6f, 0x0a, 0x16, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x61, 0x63, 0x70, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x72, 0x0a, 0x11,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73,
	0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x61, 0x63, 0x70,
	0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sourcenetwork_acp_core_catalogue_proto_rawDescOnce sync.Once
	file_sourcenetwork_acp_core_catalogue_proto_rawDescData = file_sourcenetwork_acp_core_catalogue_proto_rawDesc
)

func file_sourcenetwork_acp_core_catalogue_proto_rawDescGZIP() []byte {
	file_sourcenetwork_acp_core_catalogue_proto_rawDescOnce.Do(func() {
		file_sourcenetwork_acp_core_catalogue_proto_rawDescData = protoimpl.X.CompressGZIP(file_sourcenetwork_acp_core_catalogue_proto_rawDescData)
	})
	return file_sourcenetwork_acp_core_catalogue_proto_rawDescData
}

var file_sourcenetwork_acp_core_catalogue_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sourcenetwork_acp_core_catalogue_proto_goTypes = []interface{}{
	(*PolicyCatalogue)(nil),   // 0: sourcenetwork.acp_core.PolicyCatalogue
	(*ResourceCatalogue)(nil), // 1: sourcenetwork.acp_core.ResourceCatalogue
	nil,                       // 2: sourcenetwork.acp_core.PolicyCatalogue.ResourceCatalogueEntry
}
var file_sourcenetwork_acp_core_catalogue_proto_depIdxs = []int32{
	2, // 0: sourcenetwork.acp_core.PolicyCatalogue.resource_catalogue:type_name -> sourcenetwork.acp_core.PolicyCatalogue.ResourceCatalogueEntry
	1, // 1: sourcenetwork.acp_core.PolicyCatalogue.ResourceCatalogueEntry.value:type_name -> sourcenetwork.acp_core.ResourceCatalogue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sourcenetwork_acp_core_catalogue_proto_init() }
func file_sourcenetwork_acp_core_catalogue_proto_init() {
	if File_sourcenetwork_acp_core_catalogue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sourcenetwork_acp_core_catalogue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyCatalogue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sourcenetwork_acp_core_catalogue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceCatalogue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sourcenetwork_acp_core_catalogue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sourcenetwork_acp_core_catalogue_proto_goTypes,
		DependencyIndexes: file_sourcenetwork_acp_core_catalogue_proto_depIdxs,
		MessageInfos:      file_sourcenetwork_acp_core_catalogue_proto_msgTypes,
	}.Build()
	File_sourcenetwork_acp_core_catalogue_proto = out.File
	file_sourcenetwork_acp_core_catalogue_proto_rawDesc = nil
	file_sourcenetwork_acp_core_catalogue_proto_goTypes = nil
	file_sourcenetwork_acp_core_catalogue_proto_depIdxs = nil
}
