// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: sourcenetwork/acp_core/access_ticket.proto

/* eslint-disable */
import { type AccessDecision } from "./access_decision";

export const protobufPackage = "sourcenetwork.acp_core";

/**
 * Represents a Capability token containing an opaque proof and a set of Operations
 * the Actor is allowed to perform.
 * Tickets should be verified by a Reference Monitor before granting access to the requested operations.
 */
export interface AccessTicket {
  /** identified the ticket version */
  versionDenominator: string;
  decisionId: string;
  decision:
    | AccessDecision
    | undefined;
  /**
   * proof of existance that the given decision exists in the chain
   * validation strategy is dependent on ticket version
   */
  decisionProof: Uint8Array;
  /** signature of ticket which must match actor pkey in the access decision */
  signature: Uint8Array;
}
