// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: sourcenetwork/acp_core/parser_message.proto

/* eslint-disable */
import { type BufferInterval } from "./buffer_position";

export const protobufPackage = "sourcenetwork.acp_core";

/** LocatedMessage models a message which points to a position in a text buffer */
export interface LocatedMessage {
  message: string;
  kind: LocatedMessage_MessageKind;
  inputName: string;
  interval: BufferInterval | undefined;
}

export enum LocatedMessage_MessageKind {
  UNKNOWN = 0,
  ERROR = 1,
  INFO = 2,
  WARNING = 3,
  UNRECOGNIZED = -1,
}
