// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: sourcenetwork/acp_core/permission_expr_tree.proto

/* eslint-disable */

export const protobufPackage = "sourcenetwork.acp_core";

/**
 * Combinator expresses a set combinator which
 * merges the result of two fetch operatiosn
 */
export enum Combinator {
  COMB_UNKNOWN = 0,
  UNION = 1,
  DIFFERENCE = 2,
  INTERSECTION = 3,
  UNRECOGNIZED = -1,
}

/**
 * PermissionExpr models a permission fetch tree,
 * which controls how a permission is evaluated
 */
export interface PermissionFetchTree {
  operation?: FetchOperation | undefined;
  combNode?: CombinationNode | undefined;
}

/** CombinationNode models a term which has a left and right expr alongside a combinator */
export interface CombinationNode {
  left: PermissionFetchTree | undefined;
  combinator: Combinator;
  right: PermissionFetchTree | undefined;
}

/** FetchOperation models a terminal in the permission expr tree, meaning a single fetch operator */
export interface FetchOperation {
  cu?: ComputedUsersetNode | undefined;
  this?: ThisNode | undefined;
  ttu?: TupleToUsersetNode | undefined;
}

/** ComputedUsersetNode models a computed userset operation */
export interface ComputedUsersetNode {
  relation: string;
}

/** ThisNode models a fetch this operation */
export interface ThisNode {
}

/** TupleToUsersetNode models a Tuple to Userset operation */
export interface TupleToUsersetNode {
  lookupRelation: string;
  computedUsersetRelation: string;
}
