// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: sourcenetwork/acp_core/relationship_selector.proto

/* eslint-disable */
import { type Object, type Subject } from "./relationship";

export const protobufPackage = "sourcenetwork.acp_core";

/**
 * RelationshipSelector models a set of predicates which are used to filter through
 * Relationships in a Policy.
 */
export interface RelationshipSelector {
  objectSelector: ObjectSelector | undefined;
  relationSelector: RelationSelector | undefined;
  subjectSelector: SubjectSelector | undefined;
}

/** ObjectSelector models a filter for Relationship Objects */
export interface ObjectSelector {
  /** object specifies an object which the Relationship must contain */
  object?:
    | Object
    | undefined;
  /** wildcard matches any object */
  wildcard?: WildcardSelector | undefined;
  resourcePredicate?: string | undefined;
}

/** RelationsSelector models a filter for Relationship Relations */
export interface RelationSelector {
  /** relation specifies a relation name which must exactly match the Relationship's */
  relation?:
    | string
    | undefined;
  /** wildcard matches any relation */
  wildcard?: WildcardSelector | undefined;
}

/** SubjectSelector models a filter for Relationship Subjects */
export interface SubjectSelector {
  /** subject requires an exact match between the given subject and a Relationship's subject */
  subject?:
    | Subject
    | undefined;
  /** wildcard matches any subject in a Relationship */
  wildcard?: WildcardSelector | undefined;
}

/** WildcardSelector matches anything in a context */
export interface WildcardSelector {
}
