// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: sourcenetwork/acp_core/request.proto

/* eslint-disable */
import type { Actor, Object } from "./relationship";

export const protobufPackage = "sourcenetwork.acp_core";

/** AccessRequest represents the wish to perform a set of operations by an actor */
export interface AccessRequest {
  operations: Operation[];
  /** actor requesting operations */
  actor: Actor | undefined;
}

/** Operation represents an action over an object. */
export interface Operation {
  /** target object for operation */
  object:
    | Object
    | undefined;
  /** permission required to perform operation */
  permission: string;
}
