// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: sourcenetwork/acp_core/specification.proto

/* eslint-disable */

export const protobufPackage = "sourcenetwork.acp_core";

/** PolicySpecificationType models a named policy specification */
export enum PolicySpecificationType {
  /** NO_SPEC - NO_SPEC models a policy which has no additional contraints on it */
  NO_SPEC = 0,
  /** DEFRA_SPEC - DEFRA_SPEC models a policy which matches the Defra policy specification */
  DEFRA_SPEC = 1,
  UNRECOGNIZED = -1,
}
