// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: sourcenetwork/acp_core/system.proto

/* eslint-disable */

export const protobufPackage = "sourcenetwork.acp_core";

/** Params models the dynamic system parameters that callers can set */
export interface Params {
}

export interface BuildInfo {
  /** commit is the commit from which this build was generated */
  commit: string;
  /** version */
  version: string;
}
